/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as Admin_layoutRouteImport } from './routes/admin/__layout'
import { Route as AdminSubcategoriesIndexRouteImport } from './routes/admin/subcategories.index'
import { Route as AdminSkillsIndexRouteImport } from './routes/admin/skills.index'
import { Route as AdminExperiencesIndexRouteImport } from './routes/admin/experiences.index'
import { Route as AdminEducationIndexRouteImport } from './routes/admin/education.index'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin/categories.index'

const AdminRouteImport = createFileRoute('/admin')()

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const Admin_layoutRoute = Admin_layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubcategoriesIndexRoute = AdminSubcategoriesIndexRouteImport.update({
  id: '/subcategories/',
  path: '/subcategories/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSkillsIndexRoute = AdminSkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExperiencesIndexRoute = AdminExperiencesIndexRouteImport.update({
  id: '/experiences/',
  path: '/experiences/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEducationIndexRoute = AdminEducationIndexRouteImport.update({
  id: '/education/',
  path: '/education/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resume': typeof ResumeRoute
  '/admin': typeof Admin_layoutRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/education': typeof AdminEducationIndexRoute
  '/admin/experiences': typeof AdminExperiencesIndexRoute
  '/admin/skills': typeof AdminSkillsIndexRoute
  '/admin/subcategories': typeof AdminSubcategoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resume': typeof ResumeRoute
  '/admin': typeof AdminIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/education': typeof AdminEducationIndexRoute
  '/admin/experiences': typeof AdminExperiencesIndexRoute
  '/admin/skills': typeof AdminSkillsIndexRoute
  '/admin/subcategories': typeof AdminSubcategoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resume': typeof ResumeRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/__layout': typeof Admin_layoutRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/education/': typeof AdminEducationIndexRoute
  '/admin/experiences/': typeof AdminExperiencesIndexRoute
  '/admin/skills/': typeof AdminSkillsIndexRoute
  '/admin/subcategories/': typeof AdminSubcategoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/login'
    | '/reset-password'
    | '/resume'
    | '/admin'
    | '/admin/'
    | '/admin/categories'
    | '/admin/education'
    | '/admin/experiences'
    | '/admin/skills'
    | '/admin/subcategories'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/login'
    | '/reset-password'
    | '/resume'
    | '/admin'
    | '/admin/categories'
    | '/admin/education'
    | '/admin/experiences'
    | '/admin/skills'
    | '/admin/subcategories'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/login'
    | '/reset-password'
    | '/resume'
    | '/admin'
    | '/admin/__layout'
    | '/admin/'
    | '/admin/categories/'
    | '/admin/education/'
    | '/admin/experiences/'
    | '/admin/skills/'
    | '/admin/subcategories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResumeRoute: typeof ResumeRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/__layout': {
      id: '/admin/__layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof Admin_layoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subcategories/': {
      id: '/admin/subcategories/'
      path: '/subcategories'
      fullPath: '/admin/subcategories'
      preLoaderRoute: typeof AdminSubcategoriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/skills/': {
      id: '/admin/skills/'
      path: '/skills'
      fullPath: '/admin/skills'
      preLoaderRoute: typeof AdminSkillsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/experiences/': {
      id: '/admin/experiences/'
      path: '/experiences'
      fullPath: '/admin/experiences'
      preLoaderRoute: typeof AdminExperiencesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/education/': {
      id: '/admin/education/'
      path: '/education'
      fullPath: '/admin/education'
      preLoaderRoute: typeof AdminEducationIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  Admin_layoutRoute: typeof Admin_layoutRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminEducationIndexRoute: typeof AdminEducationIndexRoute
  AdminExperiencesIndexRoute: typeof AdminExperiencesIndexRoute
  AdminSkillsIndexRoute: typeof AdminSkillsIndexRoute
  AdminSubcategoriesIndexRoute: typeof AdminSubcategoriesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  Admin_layoutRoute: Admin_layoutRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminEducationIndexRoute: AdminEducationIndexRoute,
  AdminExperiencesIndexRoute: AdminExperiencesIndexRoute,
  AdminSkillsIndexRoute: AdminSkillsIndexRoute,
  AdminSubcategoriesIndexRoute: AdminSubcategoriesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResumeRoute: ResumeRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
